### ISSUE TITLE
Add a component to export the view from viewport name

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-grasshopper-radiance#2]

**Comment by mostaphaRoudsari** [comment]
We should use the code in honeybee legacy as a reference.

It is actually a little bit tricky to get it right in all cases and we have almost all the cases addressed already in the legacy.

**Comment by chriswmackey** [comment]
This was addressed via https://github.com/ladybug-tools/honeybee-grasshopper-radiance/pull/4
