### ISSUE TITLE
Way to install "Honeybee-grasshopper-radiance" 

### ISSUE THREAD

**Issue by SichenLu97** [ladybug-tools/honeybee-grasshopper-radiance#204]
I wonder how to install "Honeybee-grasshopper-radiance" from GitHub (https://github.com/ladybug-tools/honeybee-grasshopper-radiance) to my laptop. 

I followed a standard way (https://github.com/ladybug-tools/lbt-grasshopper/wiki/1.1-Windows-Installation-Steps).

However, some features from  "Honeybee-grasshopper-radiance" are not loaded. For example, I cannot load  "HB Imageless Annual Glare.ghuser".

Thanks!

**Comment by mostaphaRoudsari** [comment]
Hi @SichenLu97, The easiest way is to use the Pollination Grasshopper installer which also installs all the Ladybug Tools libraries: https://www.pollination.cloud/grasshopper-plugin

**Comment by SichenLu97** [comment]
Hi @mostaphaRoudsari, thanks so much for the prompt response. I did not know Pollination Grasshopper before.
