### ISSUE TITLE
Questions on carry out daylight simulation with multiple sky but a same model

### ISSUE THREAD

**Issue by FeiY92** [ladybug-tools/honeybee-grasshopper-radiance#214]
Hi, I have a problem when I use honeybee to make some CIE-sky-based point-in-time daylighting simulation. The simulation processes for a building model with several different CIE sky would carry out one after one independently, where the generation of the building model settings repeated. Although this is only about 1-2s for 1 run, it would be added up to a very long time if I have a lot of runs. 

So I am seek for help to cut down the time of the repeated model settings generate...

(I notice the settings of reload_old_, but it seems cannot solve my problem. I also tried to recode the 'point-in-time recipe' component in python to make an inner loop for multiple sky after setting the model input, but it failed... )

**Comment by mostaphaRoudsari** [comment]
Hi @FeiY92, You should post this question to the ladybug tools discourse forum: https://discourse.ladybug.tools
